# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostSyndicateTelecommunicationsOfficer
  name: job-name-typan-telecommunications-officer
  playTimeTracker: JobOutpostTypanTelecommunicationsOfficer
  salary: 65000
  description: Офицер телекомуникаций из далёкого космоса.
  startingGear: SyndicateFormal
  icon: "JobIconSyndicateFormal"
  supervisors: job-supervisors-typan-syndicate
  canBeAntag: true
  hideConsoleVisibility: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 30000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 95000
    - !type:DepartmentTimeRequirement
      department: Frontier
      time: 108000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000
    - !type:OverallPlaytimeRequirement
      time: 360000
  access:
  - SyndicateAgent
  - NuclearOperative
  - TelecomOfficer
  accessGroups:
  - AllAccess
  special:
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate
      - type: SpecialSectorStationRecord
        recordGeneration: FalseRecord
      - type: MailDisabled
      - type: NpcFactionMember
        factions:
        - LuaNordFoll

- type: startingGear
  id: SyndicateFormal
  equipment:
    eyes: ClothingEyesHudOutpostSyndicate
    ears: ClothingHeadsetAltOutpostSyndicate
    shoes: ClothingShoesBootsCombat
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    gloves: ClothingHandsGlovesCombat
    id: SyndiPDACom
    back: ClothingBackpackSyndicateFilled
    belt: ClothingBeltAssaultOutpostSyndicate
    pocket1: SyndicateWhistle
    pocket2: ClothingMaskGasSyndicate

# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: npcFaction
  id: Missile
  hostile:
  - PointDefenseGun # this will never be used but why not ykwim

- type: npcFaction
  id: PointDefenseGun
  hostile:
  - Missile

# !!!!!!HEY HEY READ THIS HEY HEY!!!!!!
# USE THE FOLLOWING FOR SHIPS ONLY I BEG
# THANK YOU!!!!!!!!!!

- type: npcFaction
  id: IndependentShip
  hostile:
    - HostileIndependentShip

- type: npcFaction
  id: HostileIndependentShip
  hostile:
    - IndependentShip

