- type: job
  id: CentralCommandSpecialOperationsOfficer
  name: job-name-centcomoso
  description: job-description-centcomoso
  playTimeTracker: JobCentralCommandSpecialOperationsOfficer
  salary: 327000
  setPreference: true
  startingGear: CentcomSpecialOperationsOfficerGear
  icon: JobIconNanotrasenRed
  supervisors: job-supervisors-no-one
  canBeAntag: false
  weight: 1
  requireAdminNotify: true
  joinNotifyCrew: true
  whitelisted: true
  requirements:
    - !type:RoleTimeRequirement
      role: JobCentralCommandOperator
      time: 21600
    - !type:RoleTimeRequirement
      role: JobCentralCommandOfficial
      time: 21600
    - !type:DepartmentTimeRequirement
      department: CentCom
      time: 31600
    - !type:DepartmentTimeRequirement
      department: Frontier
      time: 156600
  accessGroups:
    - AllAccess
    - CentCom
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - CentralCommand
        - type: AntagImmune
        - type: Company
          companyName: CentComm
